### ISSUE TITLE
[API] Update the backend

### ISSUE THREAD

**Issue by StefanOltmann** [barratt/mapsnotincluded.org#10]
The official backend should be updated to the current data structure.
Also it should be able to run the filter query.

Here is sample data to work with:
[backup_2024_10_04.json](https://github.com/user-attachments/files/17265372/backup_2024_10_04.json)

**Comment by StefanOltmann** [comment]
An updated dump of 515 worlds I collected so far - including mixing worlds.

[backup_2024_10_05.json](https://github.com/user-attachments/files/17265734/backup_2024_10_05.json)

**Comment by barratt** [comment]
Will have to decide if we're moving over to an unstructured JSON format. At present I'm wondering if we store these as JSON blobs somewhere, maybe using an 'ingest' server or something similar (could be Mongo based, or blob storage) that get processed into indexed, relational Postgres for faster queries.

**Comment by StefanOltmann** [comment]
We don’t have to use that format in the database.
You can also map this to relational tables.

**Comment by StefanOltmann** [comment]
I believe we should start building something to get the ball rolling. We can always make adjustments later, as the initial versions are typically discarded anyway.

**Comment by barratt** [comment]
Done, can you confirm and close
