### ISSUE TITLE
[MOD] Connect Steam API to identify users

### ISSUE THREAD

**Issue by StefanOltmann** [barratt/mapsnotincluded.org#11]
We want the mod to send the steam ID of the user along, so that we can delete all contributions of bad actors.

I hope we don't encounter one, but Cairath warned us that she had been dealing a lot with people trying to corrupt the database just to troll others.

This suggests that we should invest time in counter-measures.

**Comment by barratt** [comment]
Yep, I think we should try and utilise the SteamWorks API built into the game somehow, but also some form of API key generation, whether we get users to generate one or we use a custom pre-generated one for each subscriber. 

At present we keep generation private, but before we go public we will need some form of security. Probably best to keep this discussion to a private discord channel of trusted contributors

**Comment by StefanOltmann** [comment]
To my understanding the mod does that now.
