### ISSUE TITLE
Craft service that can collect the current game file hashes

### ISSUE THREAD

**Issue by StefanOltmann** [barratt/mapsnotincluded.org#12]
To prevent manipulated world generation, we want the backend to verify that the game DLLs are authentic. The mod will gather the DLL checksums and send them to the server for validation.

To automate this process, a service should fetch the current game DLLs from an API, generate a checksum for each, and upload them to a database for comparison.

**Comment by barratt** [comment]
I'm happy to write a mod that downloads the current game files, but ultimately the game will have to make an API call to us and could just spoof the correct checksums, I'm not sure what this achieves?

**Comment by barratt** [comment]
Hash service is now deployed
