### ISSUE TITLE
[WEB] Update the contributions page

### ISSUE THREAD

**Issue by StefanOltmann** [barratt/mapsnotincluded.org#13]
I suggest we update the https://mapsnotincluded.org/contribute page to remove the section about sending savegame files for indexing, as we discussed on Discord — this approach isn't effective for us.

For now, let's direct people to join the Discord, where they can access the latest version of the mod and contribute seeds.

In the future, we can upload a more robust version of the mod to the Steam Workshop and provide a link to it from the site.

**Comment by barratt** [comment]
Happy to tweak the wording, but I would like users to be able to submit seeds either through their own savegames or via seed (maybe not an API but a semi-manual process?) as naturally its RNG, someone may just get a really really awesome seed, doesn't have to be an urgent thing

**Comment by StefanOltmann** [comment]
Okay, but this should be a side note. The main way of contributing must be the mod.

Until it’s ready we can keep this issue open.

**Comment by Sgt-Imalas** [comment]
if they want to contribute the seeds, they should be using the mod, but with it allowing them to insert their seed
-> put the/a start-collection-button into the world selection

**Comment by StefanOltmann** [comment]
Was resolved.
