### ISSUE TITLE
[REPO] Pick a license and add it to the repo

### ISSUE THREAD

**Issue by StefanOltmann** [barratt/mapsnotincluded.org#15]
The mod by Sgt_Imalas is licensed under the MIT license, and I plan to keep it that way to honor his choice.

If I decide to merge the seed browser in the future (though it's not practical at the moment, as we've discussed), it would be licensed under AGPL 3.

As for the rest of the repository, which currently includes the backend and the world trait browser, a license is still needed. I recommend AGPL 3, but the final decision is yours.

**Comment by barratt** [comment]
Added AGPL 3
