### ISSUE TITLE
[MOD] Build the mod using GitHub actions

### ISSUE THREAD

**Issue by StefanOltmann** [barratt/mapsnotincluded.org#19]
We should set up a GitHub action to build the mod and bake in the API key.

**Comment by barratt** [comment]
For this we will either need a Docker image that can pull and link the DLLs from in game using SteamCMD or Sgt_lmalas stated that we can use 'reference' DLLs (which I believe Klei said we're allowed to use?) but under no circumstances should game DLLs be added to the GH repo.

**Comment by StefanOltmann** [comment]
Yes, this was the link @SGT_Imalas shared:
https://github.com/peterhaneve/ONIMods/commit/cc670765314f0b96518b7bcea09f4e009e210cce

**Comment by barratt** [comment]
🎉
