### ISSUE TITLE
Map Preview

### ISSUE THREAD

**Issue by barratt** [barratt/mapsnotincluded.org#2]
Its possible to collect a screenshot once the world is saved, submit this along with the world data to the database (Even though its a similar size to the world itself :( )

**Comment by StefanOltmann** [comment]
The original mod by Sgt_Imalas has logic for that, which we could add back in:

https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/blob/d4c6fe576c0ac90f2c57cf50ba6cc4356909ca62/_WorldGenStateCapture/ModAssets.cs#L68-L77

**Comment by StefanOltmann** [comment]
Solved.
