### ISSUE TITLE
Write a tutorial on how to use the mod to contribute seeds

### ISSUE THREAD

**Issue by StefanOltmann** [barratt/mapsnotincluded.org#25]
We need to write a manual for that and put it on the page.

**Comment by andrewcode-create** [comment]
Done :)

**Comment by StefanOltmann** [comment]
Thanks :)

I may ask you to update it and point users to the release page as soon as that works :D

**Comment by andrewcode-create** [comment]
Yup! I can update it to use the steam mod whenever its ready.

**Comment by StefanOltmann** [comment]
The steam mod comes next, yes.

By the time we may refer to both files, as it could happen that the steam mod is not updated immediately

**Comment by StefanOltmann** [comment]
@andrewcode-create People can grab the current mod (as well as the latest data export) now from the release page at https://github.com/barratt/mapsnotincluded.org/releases

That's a bit more user friendly to get it from there.

**Comment by andrewcode-create** [comment]
On it!
