### ISSUE TITLE
[Frontend] The frontend should support translations

### ISSUE THREAD

**Issue by Sgt-Imalas** [barratt/mapsnotincluded.org#30]
TNI had a major problem with a chinese group that cloned the page just to translate it.
adding translations to the page beforehand should prevent such attempts

**Comment by andrewcode-create** [comment]
How would this work? I know google translates some websites automatically with google translate...

**Comment by jason21415** [comment]
Translate txt
[ZH_TW.txt](https://github.com/user-attachments/files/17435990/ZH_TW.txt)
```
平均產出:1908克/秒
每460秒中噴發234秒 噴發量5790克/秒
活躍期:每112.4週期中活躍72.8週期
```

[ZH_CN.txt](https://github.com/user-attachments/files/17436032/ZH_CN.txt)
```
平均产出:1908克/秒
每460秒中喷发234秒 喷发量5790克/秒
活跃期:每112.4周期中活跃72.8周期
```
![image](https://github.com/user-attachments/assets/4001404d-4c74-4cf7-8a8e-5117b04da3f9)
