### ISSUE TITLE
Save worlds to disk for reupload if sending fails

### ISSUE THREAD

**Issue by barratt** [barratt/mapsnotincluded.org#34]
When a users internet connection is down, or the server is down, the mod could save worlds to disk, this would allow us to then re-upload them on the next game launch. Preventing loss of generated worlds.

**Comment by barratt** [comment]
Sgt rightfully mentioned on Discord this opens up an attack vector.

**Comment by Sgt-Imalas** [comment]
Implemented, but inactive in the mod for security reasons
