### ISSUE TITLE
game infinitely loads sometimes 

### ISSUE THREAD

**Issue by andrewcode-create** [barratt/mapsnotincluded.org#40]
Sometimes, the game seems to infinitely load on the loading screen. I left it for 10 min, nothing changed. I included the log file (player.log).

The first error is on line 957, where there is a NullReferenceException. 
It then seems to be in an infinite loop, trying to unload objects that don't exist.

This might be a game bug, not a mod bug. In that case, we should:
1) reproduce this in-game without the mod if we can, and submit a bug report to Klei
2) somehow detect this and restart the game so that seed collection can continue.

[Player.log](https://github.com/user-attachments/files/17427285/Player.log)

**Comment by Sgt-Imalas** [comment]
Patch the crashReporter to restart on crash.
this is a rare race condition that sometimes happens on returning to the main menu

**Comment by barratt** [comment]
Didn't see this here, I just made a bug report in the discord, 

Identical issues for me and Rockou https://discord.com/channels/1264658528870858882/1296744642179498014

Seems like we're beating the odds, could we implement some kind of timer, as a fallback - if not returned to mainmenu or game scene in 10 minutes, full restart?

**Comment by Sgt-Imalas** [comment]
The mod should now be able to bypass this issue. 
please reopen it if that happens again on the new version
