### ISSUE TITLE
Users should have the option so search for a specific seed

### ISSUE THREAD

**Issue by Sgt-Imalas** [barratt/mapsnotincluded.org#44]
Users should have an input field that allows them to look at a specific seed.
if that seed wasnt indexed yet, they can request it for indexing.

**Comment by barratt** [comment]
This format now works - https://mapsnotincluded.org/map-explorer/V-SNDST-C-101520169-0-0-0

Just need some kind of UI i guess?

**Comment by StefanOltmann** [comment]
Nah, I don't think there needs to be an extra UI.

**Comment by barratt** [comment]
Implemented
