### ISSUE TITLE
There should be a system in place that allows users to request seeds

### ISSUE THREAD

**Issue by Sgt-Imalas** [barratt/mapsnotincluded.org#45]
When a user searches for a specific seed (see #44 ) and the seed wasnt indexed yet, they should have the option to request it.

This should be rate limited per IP adress (for example 5 seeds / hour).

A seed stored in this way should be put in a queue.
the API then needs to have an access point for the mod instances to request a seed from.
seeds requested in this way are then put in a "in progress" queue. After 2 minutes, if the seed hasnt been added to the DB yet, it is to assume the mod that fetched it failed generating and it is inserted back into the main waiting queue.

**Comment by Sgt-Imalas** [comment]
requires #46

**Comment by Sgt-Imalas** [comment]
This system should automatically strip the story trait and the settings code part of the coordinate and replace them with the default "0" (no story traits, normal survival settings)

**Comment by StefanOltmann** [comment]
I can make endpoints in the ingest service to add a seed to the queue and request the queue. It would make sense there, so an upload of a requested map removes it from the queue.

We discussed that we'll need a form page that's protected with "Login with steam" for seed requests.
