### ISSUE TITLE
WorldTrait generator code should be implemented into a UI 

### ISSUE THREAD

**Issue by barratt** [barratt/mapsnotincluded.org#52]
7ee9d882a1530e4c87256d46e083bb98d3ff2f52 should be implemented into some form of UI so users can find specific worldTraits they are looking for

**Comment by barratt** [comment]
See tests for details on how to implement

**Comment by barratt** [comment]
I have turned this into a package now over at oniworldgen 
https://www.npmjs.com/package/oniworldgen
https://github.com/barratt/mapsnotincluded.org/tree/main/oniworldgen-js

When someone tackles https://github.com/barratt/mapsnotincluded.org/issues/56 this package will be platform agnostic ready for implementation anywhere

**Comment by barratt** [comment]
I've started implementing said package over in 82a4f23f486340090955968bb1c0f7c43e828278 

I have modified the package oniworldgen to have browser / vite / react support (oniworldgen.mjs)

I have also got most of the generation code in, we just need to sync the IDs and traits from the game into the ui (see oni.js in frontend)

Once the generation code works its just a matter of styling and filters, for example should all traits be on one specific world. all traits on any world, or any traits spread across worlds. lots to choose from and design

**Comment by Sgt-Imalas** [comment]
embedded "TraitFinder" Blazor App
