### ISSUE TITLE
Requested coordinates should check regex

### ISSUE THREAD

**Issue by StefanOltmann** [barratt/mapsnotincluded.org#67]
The coordinates should be checked by this regex:

`^(SNDST-A|CER-A|CERS-A|OCAN-A|S-FRZ|LUSH-A|FRST-A|VOLCA|BAD-A|HTFST-A|OASIS-A|V-SNDST-C|V-CER-C|V-CERS-C|V-OCAN-C|V-SWMP-C|V-SFRZ-C|V-LUSH-C|V-FRST-C|V-VOLCA-C|V-BAD-C|V-HTFST-C|V-OASIS-C|SNDST-C|CER-C|FRST-C|SWMP-C|M-SWMP-C|M-BAD-C|M-FRZ-C|M-FLIP-C|M-RAD-C)-\d+-[^-]*-[^-]*-[^-]*`

**Comment by barratt** [comment]
Great thanks for this I'll get it implemented

**Comment by barratt** [comment]
Sgt took care of this, just merged it in
