### ISSUE TITLE
[MOD] The mod should upload checksums of game files

### ISSUE THREAD

**Issue by StefanOltmann** [barratt/mapsnotincluded.org#9]
To prevent invalid seed data by modded worldgen code we should check the games DLLs.

For that the mod should upload a checksum of the files and send that to the server.

The server should request the Steam API to keep up to date with valid game DLL files.

**Comment by barratt** [comment]
Linked to #12

**Comment by Sgt-Imalas** [comment]
included in the latest mod builds.
the api needs to be adjusted to allow this new data

**Comment by Sgt-Imalas** [comment]
this is implemented for all files that are part of the current seeds worldgen
